### ISSUE TITLE
ceph-volume lvm --bluestore fails on 12.2.2

### ISSUE THREAD

**Issue by rdoerr01** [ceph/ceph-volume#4]
I just upgraded my CEPH nodes to 12.2.2 and I wanted to see if "ceph-volume lvm --bluestore" would now work for creating a Bluestore OSD using LVM, and in particular using a partition on my SSD.  Here are the steps I took.

fdisk /dev/nvme0n1
  Create partition #7 with +128Gib of space.

pvcreate /dev/nvme0n1p7
vgcreate ceph /dev/nvme0n1p7
lvcreate --name ssd --extents 100%FREE ceph

ceph-volume lvm prepare --bluestore --data ceph/ssd

[root@compute-1 ~]# ceph-volume lvm prepare --bluestore --data ceph/ssd
Running command: sudo mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-8
Running command: chown -R ceph:ceph /dev/dm-0
Running command: sudo ln -s /dev/ceph/ssd /var/lib/ceph/osd/ceph-8/block
Running command: sudo ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-8/activate.monmap
 stderr: got monmap epoch 4
Running command: ceph-authtool /var/lib/ceph/osd/ceph-8/keyring --create-keyring --name osd.8 --add-key AQBpJiRaoSApKRAA+fIm5sPHuCROoKg30hMebA==
 stdout: creating /var/lib/ceph/osd/ceph-8/keyring
 stdout: added entity osd.8 auth auth(auid = 18446744073709551615 key=AQBpJiRaoSApKRAA+fIm5sPHuCROoKg30hMebA== with 0 caps)
Running command: chown -R ceph:ceph /var/lib/ceph/osd/ceph-8/keyring
Running command: chown -R ceph:ceph /var/lib/ceph/osd/ceph-8/
Running command: sudo ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 8 --monmap /var/lib/ceph/osd/ceph-8/activate.monmap --key **************************************** --osd-data /var/lib/ceph/osd/ceph-8/ --osd-uuid b7012c22-a5a1-4694-9aa7-e8242e17a051 --setuser ceph --setgroup ceph
 stderr: 2017-12-03 10:29:30.426562 7f909c032d00 -1 bluestore(/var/lib/ceph/osd/ceph-8//block) _read_bdev_label unable to decode label at offset 102: buffer::malformed_input: void bluestore_bdev_label_t::decode(ceph::buffer::list::iterator&) decode past end of struct encoding
 stderr: 2017-12-03 10:29:30.426739 7f909c032d00 -1 bluestore(/var/lib/ceph/osd/ceph-8//block) _read_bdev_label unable to decode label at offset 102: buffer::malformed_input: void bluestore_bdev_label_t::decode(ceph::buffer::list::iterator&) decode past end of struct encoding
2017-12-03 10:29:30.426891 7f909c032d00 -1 bluestore(/var/lib/ceph/osd/ceph-8//block) _read_bdev_label unable to decode label at offset 102: buffer::malformed_input: void bluestore_bdev_label_t::decode(ceph::buffer::list::iterator&) decode past end of struct encoding
 stderr: 2017-12-03 10:29:30.427016 7f909c032d00 -1 bluestore(/var/lib/ceph/osd/ceph-8/) _read_fsid unparsable uuid
 stderr: 2017-12-03 10:29:31.460639 7f909c032d00 -1 key AQBpJiRaoSApKRAA+fIm5sPHuCROoKg30hMebA==
 stderr: 2017-12-03 10:29:31.970919 7f909c032d00 -1 created object store /var/lib/ceph/osd/ceph-8/ for osd.8 fsid e4fa05c5-6965-4832-9e89-c6f7cebe5b7b

I'm not sure what is going wrong here, does this look correct with the double slash in the path?
  /var/lib/ceph/osd/ceph-8//block

**Comment by alfredodeza** [comment]
This repository got moved into ceph, thanks for reporting this, please use http://tracker.ceph.com/projects/ceph-volume/issues/new next time.

What you are seeing here is malformed output from the OSD, I don't think there is anything ceph-volume can do here
